apiVersion: v1
kind: Service
metadata:
  name: validacaoad-service
  namespace: producao
  labels:
    app: validacaoad
spec:
  selector:
    app: validacaoad
  ports:
    - name: http
      protocol: TCP
      port: 8089
      targetPort: 8089
      nodPort: 31007
  type: LoadBalancer  # Ou NodePort
